# Generated by Django 4.2.3 on 2024-03-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
