# Generated by Django 4.2.3 on 2024-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_usercourse_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor_domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
    ]
