# Generated by Django 4.2.3 on 2024-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_instructor_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor_domain',
        ),
        migrations.AddField(
            model_name='author',
            name='domain',
            field=models.CharField(default='devloper', max_length=100, null=True),
        ),
    ]
