# Generated by Django 4.2.3 on 2024-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_instructor_domain_author_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='domain',
            field=models.CharField(default='Devloper', max_length=100, null=True),
        ),
    ]
