# Generated by Django 4.2.3 on 2024-03-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_author_gender_author_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.categories'),
        ),
    ]
