# Generated by Django 4.2.3 on 2024-03-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_author_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
    ]
