# Generated by Django 4.2.3 on 2024-03-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
