# Generated by Django 4.2.3 on 2024-03-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_video_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='name',
        ),
    ]
